language: node_js
node_js:
- 5.0.0
- 6.0.0
- 7.0.0
- 8.0.0
sudo: false
install:
- npm install
before_deploy:
- npm run build
deploy:
  provider: npm
  email: sampastoriza@yahoo.com
  skip_cleanup: true
  api_key:
    secure: Q61GethJYrmESXyeoK423ILY6WEuR8QRl7h2N8TJ5Yxthrd9meoMa9T4gHY3WYdqHGDARi5CpZ1uchLMkU5AYfzPpK4w+pRIkUs9a6EUe3zGDc8TJkHzS3DahAsparat3wH43UULJZdBWS00d3eIofsK8OrSr4JB1ZxmEbPg+KKNhzWzZC+uCMHAwMuD2r5rfc4EMHWSB0z5IBD1ZuqGLRLmz9TFpOkI41Cl4XLWVK4jBg4QRkh2k/IEUIWEgfYBk8DjpZJqE4i5xCjsV3LpapAGr6uIj/Q5lQGWW4Rxkl5+ALq0AR6tg0OGkEN12LbPzM/LFLysz+ku4v6/bT66Uw36AT+wOuMsZM/c5aim2J51MZH6OBpDp84VcWD/vYen2MV0HoslrD+n+O0GiBLn/78uUamYJpfbsRDpiDADCJzmn0hz56XvHvudua3axo4wq08xWXOV+5OcH40eOQd3I7jha/IuzSg5Xt8eJ9UZBPtILcqE0nWds8MQiLRPcsGVf7TUZIlY7Hq5K37RSOKwQBwYfaAOJR6QwT374wNMDtoJ8Jy/LSjt78wYogZSmUawkPGkN4H7JAKLRXkAyXDs85AQMzIYGmFafQCD14lGi2d7tHNdXsIUSUqGR4WE3Ux0WUxynGpc+CYmPmrsGpKfrH4PHbkY8fgZcjD0+IcP34k=
  on:
    branch: master
    tags: true