language: node_js
node_js:
- 8.5.0
sudo: false
addons: # get google-chrome-stable
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - npm install
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - npm test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: sampastoriza@yahoo.com
  skip_cleanup: true
  api_key:
    secure: YqIhmDFPaWZnMsKEOC4T0YMjtT4yXf2sVGtbWCctkO5NY+MEWx0xOtYAA0RQ6CAu4XATu69+E1tUfF4noIeS0hPCHFFHgToHeesGaWU1T9xcJAMw8LwUgqkR37GYTvXJweUE/SNhErPIeRX+P3ipq8pVzOwH6Tqy2vRmSyK8shkoKnCdkWjPUTSfAvY5MnoTBva2PYwcCMDIVjnq/mOd19RtDUPYMYYJ8GXy8yejs2G8hVq8q5pV2L1mu/aNeK7USxA0q+t85CyBIPKBRAOAihxTqanGiC/ZMs1tHUCR38A1sc6phVVXdHm6vS9Ykd0qqX057Fh5EXkgCHG6RtEU4cyiUuShMFMDGQdCo4yPs7xezjPth3U7+Sq35gu6YN1Rvo5z58+MKE74QZQs6hIwWAeeWZr8s1xVRJLf7f5rkWD7vBzNc9uTYqKR81hWfpFVwXOBac2Mu7bl7kE2SrrSzA5UYUvr+CxzluxiGWk5HNIRGeVoOWGBGqp15R80EoDxdCXXo5beXv76+d77a6mtEHPuEVXskn8iIsjn1at2xOi/OwYC4QiOUfAvhjoca0xhdnT5v4zMJ6O+avBIC+csn2tDmvS9gG+9LnDqG0BAtABqjj9+rJqklj3GD+H+gICXP6lsHBPehUPuPel/dbb9sJh7+rx8wwDzJDgqRJfdJpo=
  on:
    branch: master
    tags: true
